# Generated by Django 3.2.4 on 2021-06-27 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo', models.CharField(max_length=5)),
                ('Preço', models.DecimalField(decimal_places=2, max_digits=9)),
                ('Quantidade', models.IntegerField()),
                ('Data', models.DateField()),
            ],
        ),
    ]
